apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing-java
  namespace: testing-java
  labels:
    app: testing-java
    managed-by: backstage
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: testing-java.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: testing-java
            port:
              number: 80
