apiVersion: v1
kind: Service
metadata:
  name: testing-java
  namespace: testing-java
  labels:
    app: testing-java
    managed-by: backstage
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: testing-java
